### ISSUE TITLE
Error using JSON commands

### ISSUE THREAD

**Issue by ryanwoconnor** [softScheck/tplink-smartplug#16]
ryBook:tplink-smartplug ryanoconnor$ python tplink-smartplug.py -t 192.168.1.225 -j {"emeter":{"get_daystat":{"month":6,"year":2017}}}

usage: tplink-smartplug.py [-h] -t <ip> (-c <command> | -j <JSON string>)

tplink-smartplug.py: error: unrecognized arguments: {emeter:{get_daystat:year:2017}}

Any idea why this would be happening?

**Comment by percidae** [comment]
I've had the same problem. I experimented with the string and this solved it for me:
``
user@mylaptop ~/Downloads/tplink-smartplug $ python tplink-smartplug.py -t 192.168.178.57 -j '{"emeter":{"get_daystat":{"month":11,"year":2017}}}'
``

**Comment by ryanwoconnor** [comment]
Interesting, it might just be an issue of needing single quotes? D’oh! I’ll give it a shot tonight and let you know if this resolves it.

Thanks!
Ryan

**Comment by softScheck** [comment]
Quotation issue. closed.
