### ISSUE TITLE
Two very minor issues with README.md

### ISSUE THREAD

**Issue by gowenfawr** [softScheck/tplink-smartplug#19]
I noticed two very minor issues with README.md:

1. In the first section ("tplink-smartplug.py")  the Usage example references a different name for the python script:

`./tplink-smarthome.py -t <ip> [-c <cmd> || -j <json>]`

That should be tplink-smartplug.py to match the file in the repo.

2. In the Command table just below that, it lists the `system` command with description `Returns device info`.  In fact, the `info` command does that and the `system` command is not recognized:

```
$ ./tplink-smartplug.py -t 192.168.0.229 -c system
usage: tplink-smartplug.py [-h] -t <ip> (-c <command> | -j <JSON string>)
tplink-smartplug.py: error: argument -c/--command: invalid choice: 'system' (choose from 'reset', 'schedule', 'antitheft', 'wlanscan', 'info', 'on', 'off', 'reboot', 'countdown', 'time', 'cloudinfo')
$ ./tplink-smartplug.py -t 192.168.0.229 -c info
Sent:      {"system":{"get_sysinfo":{}}}
Received:  {"system":{"get_sysinfo":{"err_code":0,"sw_ver":"1.1.1 Build 160725 Rel.163650","hw_ver":"1.0","type":"IOT.SMARTPLUGSWITCH","model":"HS100(US)",...
```

Awesome tool, loved the Reverse Engineering document.

**Comment by softScheck** [comment]
Thank you, fixed!
