### ISSUE TITLE
RQ: add MAC to parse commandline arguments

### ISSUE THREAD

**Issue by AlfaBravoX** [softScheck/tplink-smartplug#2]
Hi, 

we always know HW addr rather then IP. Can you add MAC address as option to parse commandline arguments? 

-m as option?

.. and then
# !/usr/bin/env python

import commands
ip = commands.getoutput("ip neighbor | grep 'xx:xx:xx:xx:xx:xx' | cut -d ' ' -f 1")

or better way then this..

**Comment by softScheck** [comment]
We would like to keep this script as simple as possible... finding the IP address shouldn't be too hard once you are in the same network! There are tools like nmap for this...
