### ISSUE TITLE
schedule

### ISSUE THREAD

**Issue by Donal2** [softScheck/tplink-smartplug#29]
how does the schedule work?
what are stime_opt, smin, etime_opt, emin, eact keys ?
thanks

**Comment by fernando-p-jesus** [comment]
Hi,
s* is for start time, while e* is for end time. I found out that you can actually use smin and emin to add a rule that, for instance, turns on at 1am and turns off at 2am. The keys would be:

stime_opt:0
smin: 60
sact:1 (1 to turn on, 0 to turn off)
etime_opt:0
emin:120
eact:0

Note that in the APP (at least in the iPhone app, I don't know if it is the same for the android app) you can only define the values for s*. So if you want the same result as above with the app, you will need to create two separate rules. Also note that when you edit the rule in the app, the e* settings will be lost.

**Comment by sisephus** [comment]
So what about the other key keys? 
Such as, is there a prescription for creating a rule-list id for the  schedule? 
    If so, how does one create a valid one or does any (non-preexisting) 32 hex-digit sequence do?
