### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by iqmeta** [softScheck/tplink-smartplug#3]
Hi,
thanks for the great reverse job...:+1:

Here my C# port https://github.com/iqmeta/tplink-smartplug

Cheers :v:

**Comment by jonnywilliamson** [comment]
Just another note to say thank you as well!

I've ported to PHP.  https://github.com/jonnywilliamson/tplinksmartplug

**Comment by softScheck** [comment]
Thank you guys :)
