### ISSUE TITLE
License for copied code?

### ISSUE THREAD

**Issue by HankB** [softScheck/tplink-smartplug#31]
Thank you for this contribution. I have copied some code from tplink-smartplug.py  and wish to confirm that I have complied with the license and provided proper attribution. Please review https://github.com/HankB/home_automation-MQTT-sensors/tree/master/DS18B20 and frmn.py in particular and let me know if I need to do anything else or different to comply.

Thanks!

**Comment by softScheck** [comment]
Everything is alright.
