### ISSUE TITLE
Run tplink-smartplug on Windows win_inet_pton

### ISSUE THREAD

**Issue by jhalbrecht** [softScheck/tplink-smartplug#34]
I had occasion to try `tplink-smartplug.py `on ms windows. I received this error.
```
> python --version
> Python 2.7.14
[...]
socket.inet_pton(socket.AF_INET, ip)
AttributeError: 'module' object has no attribute 'inet_pton'
```
I fixed it after reading on StackOverflow [Socket has no `inet_pton` method in Python 2.7 on Windows](https://github.com/mitsuhiko/python-geoip/issues/4)
```
pip install win-inet-pton
// and in the .py
import win_inet_pton
```
Suggestion; Is there a FAQ or some documentation where someone with write privilege could add this?

**Comment by softScheck** [comment]
No windows support...
