### ISSUE TITLE
Working on Windows

### ISSUE THREAD

**Issue by schierkolk** [softScheck/tplink-smartplug#4]
Fun piece of code. 

I noticed that socket.inet_pton doesn't work on Window Python 2.7
You have to pip install win-inet-pton and import win_inet_pton

**Comment by GeorgeIoak** [comment]
Thanks for posting that. I too was having problems getting it to run on Windows and that worked for me

**Comment by willcun** [comment]
Guys...   Can you help a newbie out.  I have installed Python 3.5 (C:\Program Files\Python) and I am trying to run the scripts listed here and I keep getting the below error:

 File "C:\Program Files\Python35\Lib\tddp-client.py", line 5
   <!DOCTYPE html>


![image](https://cloud.githubusercontent.com/assets/15107488/22412623/79c20436-e67e-11e6-8bbb-e9303479f254.png)

**Comment by willcun** [comment]
Ok Guys its the newbie again.  I down graded to Python 2.7 and I seen that doesn't make any difference.  I copied and pasted the raw code into notepad and saved it as a .py.  Below is the screen shot that I am getting with an error on line 76 of the code.  The code looks fine to me:

![image](https://cloud.githubusercontent.com/assets/15107488/22413415/9935756c-e685-11e6-80a6-612de191e37c.png)

**Comment by GeorgeIoak** [comment]
@willcun  Did you do what @schierkolk did? I think the errors you're getting are similar to what I was seeing before I installed and imported win-inet-pton

**Comment by willcun** [comment]
@GeorgeIoak thanks for the quick response!!  I imported the module and now I am up and running!!  What I am doing is I have extended my UPS by adding car batteries to it so my computer lab can stay off the grid for a little while.  I'm trying to trim my electric bill.  lol....  I have configured a task sequence that runs when the UPS writes to the Windows Event Viewer.   When the run time on the UPS gets very low it triggers the task sequence which will turn the smart plug on and run for a given amount of time to recharge the batteries via battery tender or the UPS itself.

Thanks again!!

**Comment by Raito00** [comment]
Hi!
I am using first time phyton ... 
i install win-inet-pton, 
but problem for me is how to import win-inet-pton?

Please explain step buy step how to import win-inet-pton

Thanks in advance!

**Comment by Raito00** [comment]
I found ! :)

Just need add line: import win-inet-pton
 in tplink-smartplug.py

**Comment by maxdad** [comment]
I am getting this when running on Windows, even after the above mentioned fix, with Python 3.6.2:

>.\tplink-smartplug.py -t 192.168.1.220 -c info
Traceback (most recent call last):
  File "C:\Down\tplink-smartplug-master\tplink-smartplug.py", line 93, in <module>
    sock_tcp.send(encrypt(cmd))
TypeError: a bytes-like object is required, not 'str'

**Comment by mlametta** [comment]
I've done this, I get what looks like a successful sending of a command but the device does not respond.  It seems to work when run on my raspberry pi though.  Not sure if it's my user error.

![tplink](https://user-images.githubusercontent.com/16610934/30565440-430b370e-9c96-11e7-8510-bf9a0f89b0c2.PNG)

**Comment by bkrajendra** [comment]
I'm also getting empty response. I'm trying with tp-link smart socket mini.

**Comment by Raito00** [comment]
I only get it work on Python V2.7
Newer versions get only errors...

**Comment by bkrajendra** [comment]
I'm on python2.7, still getting error!

**Comment by molexx** [comment]
This works straight away for me using cygwin and the python installed using its installer.

**Comment by Solarbytes** [comment]
To those getting an empty response, I had the same issue and it was due to a special decrypt code required for the Australian version of the plug. You will find the required tweak in another issue on this page.

**Comment by mlametta** [comment]
Looks like this is the issue you are talking about: https://github.com/softScheck/tplink-smartplug/issues/22
Going to give this a try, thanks.

**Comment by Solarbytes** [comment]
Correct and it works. I do get a response. I am however facing another issue: the script randomly hangs without an identifiable reason. Itvused to trigger the socket error handler and exit, now I have inserted a retry loop and it just hangs for periods of 1 minute or so. I will post a followup if I can figure out how to solve it.

**Comment by softScheck** [comment]
Seems like this is solved.
