### ISSUE TITLE
Not working on latest hardware v3.0, firmware v1.5.2

### ISSUE THREAD

**Issue by thiemob** [softScheck/tplink-smartplug#41]
I can't get the script running on a newly purchased HS110(EU).
Device label says it's HW v3.0, Kasa app however says it's HW v2.0... Firmware is on 1.5.2 (Build 180130) as per Kasa info.

If I send a request I get an empty response:
`MacBook-Pro:~ user$ downloads/tplink-smartplug-master/tplink-smartplug.py -t 192.168.5.xx -c on`
`Sent:      {"system":{"set_relay_state":{"state":1}}}`
`Received:`

Running the same thing on my trusty HS100(EU) v1.0 on FW v1.1.3 is working as intended.
`MacBook-Pro:~ user$ downloads/tplink-smartplug-master/tplink-smartplug.py -t 192.168.5.xx -c on`
`Sent:      {"system":{"set_relay_state":{"state":1}}}`
`Received:  {"system":{"set_relay_state":{"err_code":0}}}`

Just randomly sending requests to other devices gives me the following:
`MacBook-Pro:~ user$ downloads/tplink-smartplug-master/tplink-smartplug.py -t 192.168.5.xx -c info`
`Cound not connect to host 192.168.5.xx:9999`

Port 9999 therefore seems to be open on new versions, but it looks like TP-Linked changed something in between.

**Comment by cbz** [comment]
Using a HS100 on V2 with v1.5.2 firmware, I see the Kasa App appears to be still sending messages in the same format to the endpoint:

{"system":{"get_sysinfo":{}}}

However, replaying this message to the plug via the script just results in the connection hanging (or returning straight away).

**Comment by tricoos** [comment]
Just got my new one today with exactly the same problem and version difference (i.e. label says V3 and app says 2.0) - however mine has the firmware version 1.4.3 and it's also not working.
A port scan shows that port 9999 is still open and the only open port.

**Comment by tricoos** [comment]
Oh, it's working if you replace the encrypt method with this one:
`def encrypt(string):

    key = 171
    result = "\0\0\0"+chr(len(string))
    for i in string:
            a = key ^ ord(i)
            key = a
            result += chr(a)
    return result`
Found this code on https://github.com/softScheck/tplink-smartplug/issues/22#issuecomment-331464459

This gives me
`{"system":{"get_sysinfo":{"sw_ver":"1.4.3 Build 171009 Rel.104144","hw_ver":"2.0","type":"IOT.SMARTPLUGSWITCH","model":"HS110(EU)","mac":"....`

**Comment by tricoos** [comment]
They also changed the return format for `emeterGetRealtimeData `from this:
`Received:  {"emeter":{"get_realtime":{"current":0.725381,"voltage":228.570117,"power":95.750014,"total":173.236000,"err_code":0}}}`
to this:
`Received:  {"emeter":{"get_realtime":{"voltage_mv":229153,"current_ma":28,"power_mw":0,"total_wh":0,"err_code":0}}}`

They not only changed the names but also the format obviously

**Comment by cbz** [comment]
That change worked - thanks.  One of the other branches had it coded as:

**Comment by rct** [comment]
Since there are a number of PRs that aren't getting merged, Is anyone maintaining a somewhat up-to-date fork?

**Comment by cbz** [comment]
You can take a look at some of the forks that have later commit dates, but for the most part they are point fixes. I think no one really wants to have to maintain the DES related code, and that stops people from forking.
