### ISSUE TITLE
Latest Firmware changes 4 byte prefix

### ISSUE THREAD

**Issue by mkillock** [softScheck/tplink-smartplug#44]
I bought a H110 UK version plug, ran the firmware update and discovered this no longer works. However, after running a packet capture on my phone, I can see that the four byte prefix is no longer

0x00 0x00 0x00 0x00

but

0x00 0x00 0x00 0x2a

And making that change to the encode function of this https://github.com/EgoManiac/TPlink-PoSH

made it work again.

**Comment by softScheck** [comment]
Thank you. Implemented this in the current version of the Python script.
