### ISSUE TITLE
Not working on windows 10

### ISSUE THREAD

**Issue by rac8006** [softScheck/tplink-smartplug#46]
I tried to get this to work on my Windows 10 system.  I installed the modules in the proper place.  But when I tried to import the module it failed.  That problem was because the directory name was called TPLink-PlugController-PowerShell-master.  But the file in that directory was called TPLink-PlugController-PowerShell.psd1.  When I renamed the file TPLink-PlugController-PowerShell-master.psd1 the import module worked.
Next it would not find my smartplug.  After a lot of debugging it was determined that my smartplug
was not in the oui.txt file.  I added my TP-Link entry with 169182.  Now it finds the smartplug.

**Comment by softScheck** [comment]
No windows support...
