### ISSUE TITLE
TpLink HS300 Powerstip

### ISSUE THREAD

**Issue by rtmurphy** [softScheck/tplink-smartplug#48]
Hello.  Just wondering if anyone has commands for the HS300 powerstrip.  Purchased one today, it uses many of the commands from the HS1xx plug series, but need to know how to control individual relays.

**Comment by haguenau** [comment]
The original article mentions finding the list of commands by intercepting traffic from the Android Kasa app (if I understand correctly); I wish there was a bit more detail in that explanation. That would make it easier to discover commands added with new devices.
As a side note, I'm a tiny bit disappointed that the exhaustive (?) list of commands was not derived from the device-side server binary; that technique would allow discovering even commands that the mobile app does not use yet.

**Comment by rtmurphy** [comment]
I have been compiling a list of commands  for the HS300 over the past few days for my C# library.  I will make the json commands available when I have finished, if anyone is interested.

**Comment by jimboca** [comment]
Yes, we would be interested.  We are in the process of adding control for this device to the python library https://github.com/GadgetReactor/pyHS100/issues/131
