### ISSUE TITLE
Please accept one of the pull requests for clean json output.

### ISSUE THREAD

**Issue by leifnel** [softScheck/tplink-smartplug#54]
Pull request #15 #51 and #53 all provides patches for giving clean parsable json without extra text.

Please accept one of them, preferable mine, as it is backward-compatible ;-)

Without -q it works as usual.

**Comment by sylvandb** [comment]
I liked your approach for backwards compatible, but not the 'quiet' choice. I put it in my fork as -n / --naked-json .  Mine has diverged quite a bit so could not just cherry-pick your change anyway.

**Comment by softScheck** [comment]
Merged your commit.
