### ISSUE TITLE
Extra " in JSON documentation commands, file tplink-smarthome-commands.txt

### ISSUE THREAD

**Issue by jmllamasg** [softScheck/tplink-smartplug#63]
File tplink-smarthome-commands.txt

Where it says:
Get Montly Statistic for given Year
{"emeter":{""get_monthstat":{"year":2016}}}

It should say:
Get Montly Statistic for given Year
{"emeter":{"get_monthstat":{"year":2016}}}

With the extra ", the call to the command:
./tplink_smartplug.py -t IP_plug -j '{"emeter":{""get_monthstat":{"year":2019}}}'
returns nothing.

Merry Christmas!

**Comment by softScheck** [comment]
Fixed! Thanks :)
