### ISSUE TITLE
Extraneous 'f' in tplink_smartplug.py causing Python error

### ISSUE THREAD

**Issue by Maxhawkgt** [softScheck/tplink-smartplug#84]
Just tried this script for the first time and got Python errors. Digging into the code turned up an extra character in lines 90 and 135 causing the issue. I removed the extra 'f' and now it works. I apologize if I'm not using the proper way to push suggested changes (aka I'm a github noob).

`parser = argparse.ArgumentParser(description=f"TP-Link Wi-Fi Smart Plug Client v{version}")`

`    quit(f"Could not connect to host {ip}:{port}")`

**Comment by Jeppedy** [comment]
That is a formatted string part of later versions of Python...
