### ISSUE TITLE
[Request] Better handling of JSON -j option

### ISSUE THREAD

**Issue by thefinalwolf** [softScheck/tplink-smartplug#9]
Great script, just wanted to mention the -j option doesn't work unless you escape the "s .
Example: 
`tplink-smartplug.py -t <IP> --json {"system":{"get_sysinfo":null}}` 
should be typed out as
`tplink-smartplug.py -t <IP> --json {\"system\":{\"get_sysinfo\":null}}`
or simply 
`tplink-smartplug.py -t <IP> --json '{"system":{"get_sysinfo":null}}'`  (note the surrounding 's)

Maybe have the script better handle the input?

**Comment by allotmentearthy** [comment]
like above also discovered that script only worked while "escaping" commands with simple quote
which is kind of standard considering the  brackets and "  (under linux)
But this would be great to mention in the example and readme

**Comment by Solarbytes** [comment]
Just my 2 cents, I added the entries that I needed in the initial mapping of cmd to json, it makes the typing shorter and more intuitive.

**Comment by softScheck** [comment]
Use single quotes, please!
